# Generated by Django 4.0.1 on 2022-01-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
