# Generated by Django 4.0.1 on 2022-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userfollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollows',
            old_name='user',
            new_name='following_user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('following_user', 'followed_user')},
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(to='authentication.UserFollows', verbose_name='suit'),
        ),
    ]
