# Generated by Django 4.0.1 on 2022-01-24 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_user_userfollows_following_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
        migrations.AddField(
            model_name='user',
            name='following_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='suivre'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
