# Generated by Django 4.0.1 on 2022-01-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userfollows_user_follows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='followed_user',
        ),
    ]
