# Generated by Django 4.0.1 on 2022-01-28 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_follows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='following_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='suivre'),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('users', 'followed_user')},
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='following_user',
        ),
    ]
