# Generated by Django 4.0.1 on 2022-02-01 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_user_followed_alter_userfollows_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_user',
            field=models.ManyToManyField(blank=True, related_name='followed', to=settings.AUTH_USER_MODEL, verbose_name='suivi par'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
